### PR TITLE
Feature/cmake kits v2

### PR DESCRIPTION
**Pull request by mark2185**

### CODE REVIEW

**Comment by mark2185** [comment]
@ilyachur the problems on windows were the `echom 'SKIPPED'` messages, when the screen's vertical is filled, you need to press a button to continue, and that can't happen on CI.

**Comment by ilyachur** [comment]
> @ilyachur the problems on windows were the `echom 'SKIPPED'` messages, when the screen's vertical is filled, you need to press a button to continue, and that can't happen on CI.

Uhhh, my mistake! How did you understand it?
Honestly on Windows I always have a big terminal window 😄

**Comment by mark2185** [comment]
> Uhhh, my mistake! How did you understand it?
> Honestly on Windows I always have a big terminal window 😄

Pure luck! I ran the tests on windows in a small `cmd` and 1 test failed, it was a weird message so I tried it again. Then I figured out what the message was saying...

> Thank you that you have found the issue. It is a surprise for me.

No problem! I'm glad the windows builds will no longer hold my PR's open! :)

**Comment by ilyachur** [comment]
> > Uhhh, my mistake! How did you understand it?
> > Honestly on Windows I always have a big terminal window 😄
> 
> Pure luck! I ran the tests on windows in a small `cmd` and 1 test failed, it was a weird message so I tried it again. Then I figured out what the message was saying...
> 
> > Thank you that you have found the issue. It is a surprise for me.
> 
> No problem! I'm glad the windows builds will no longer hold my PR's open! :)

Yeah, it is great that the hang was fixed.

**Comment by mark2185** [comment]
@ilyachur  Should I write more tests for the coverage, or?

**Comment by ilyachur** [comment]
> @ilyachur Should I write more tests for the coverage, or? Because I tested everything new, and I've been using this PR for a month now, it worked well so far.

@mark2185 Do you have an access to coverage report?

I think will be easy to add the test to cover these lines (autoload/cmake4vim.vim:189-190):
```
186		+	" Functions allows to switch between cmake kits
187		+	function! cmake4vim#SelectKit(name) abort
188		+	    if !has_key( g:cmake_kits, a:name )
189		+	        echom printf("CMake kit '%s' not found", a:name)
190		+	        return
191		+	    endif
```

and also I see that next lines are not covered: 

autoload/utils/cmake.vim:59
```
58		+	    if !empty(g:cmake_build_path_pattern)
59		+	        return s:getCMakeBuildPattern()
60		+	    endif
```
autoload/utils/cmake.vim:100
```
98		+	function! utils#cmake#joinUserArgs(cmakeArguments) abort
99		+	    if type(a:cmakeArguments) == v:t_string
100		+	        return a:cmakeArguments
101		+	    endif
```

What do you think about these lines? Any ideas how can we cover these lines?
I see that you have done a good job, and other changes are covered. I am ok to merge this PR as is, if you don't have idea how to cover these lines

**Comment by mark2185** [comment]
> @mark2185 Do you have an access to coverage report?

I do not, I'll create an account if it's necessary.

> I think will be easy to add the test to cover these lines (autoload/cmake4vim.vim:189-190):
> 
> ```
> 186		+	" Functions allows to switch between cmake kits
> 187		+	function! cmake4vim#SelectKit(name) abort
> 188		+	    if !has_key( g:cmake_kits, a:name )
> 189		+	        echom printf("CMake kit '%s' not found", a:name)
> 190		+	        return
> 191		+	    endif
> ```

I'll add a test for this, it's simple.

> autoload/utils/cmake.vim:59
> 
> ```
> 58		+	    if !empty(g:cmake_build_path_pattern)
> 59		+	        return s:getCMakeBuildPattern()
> 60		+	    endif
> ```

Huh, this `if` is actually not necessary. I'll remove it!

> ```
> 98		+	function! utils#cmake#joinUserArgs(cmakeArguments) abort
> 99		+	    if type(a:cmakeArguments) == v:t_string
> 100		+	        return a:cmakeArguments
> 101		+	    endif
> ```

I can write a test for this too!

**Comment by ilyachur** [comment]
> I do not, I'll create an account if it's necessary.

You can use github account to login on codecov. I hope after that you should have an access to the coverage report. If no, please notify me.

> I'll add a test for this, it's simple.
> 
> Huh, this `if` is actually not necessary. I'll remove it!
> 
> I can write a test for this too!

Cool!

**Comment by ilyachur** [comment]
@mark2185 Thank you for contribution!

**Pull request merged**
